[package]
name = "by-types"
version = "0.1.2"
edition = "2021"
description = "Biyard data types"
license = "Apache-2.0"
keywords = ["axum", "datatypes", "api" ]
repository = "https://github.com/biyard/rust-sdk/tree/main/packages/by-types"

[dependencies]
serde = "1.0.217"
aide = { workspace = true,  optional = true }
axum = { workspace = true, optional = true }
schemars = { workspace = true, optional = true }
reqwest = "0.12.12"

[features]
server = [ "aide", "axum", "schemars"]
