[package]
name = "by-types"
version = "0.3.9"
edition = "2021"
description = "Biyard data types"
license = "Apache-2.0"
keywords = ["axum", "datatypes", "api" ]
repository = "https://github.com/biyard/rust-sdk/tree/main/packages/by-types"

[dependencies]
serde = { version = "1.0.217", features = ["default", "derive"] }
aide = { workspace = true,  optional = true }
axum = { workspace = true, optional = true }
schemars = { workspace = true, optional = true }
reqwest = "0.12.12"
sqlx = { version = "0.8.*", features = [
    "sqlite",
    "postgres",
    "runtime-tokio",
    "time",
    "bigdecimal",
], optional = true }
validator = "0.20.0"
tracing = "0.1.41"
serde_json.workspace = true

[features]
server = [ "aide", "axum", "schemars", "sqlx"]
