[package]
name = "btracing"
version = "0.1.2"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository = "https://github.com/biyard/rust-sdk/tree/main/packages/btracing"
description = "tracing logger interacting with notification"

[dependencies]
dioxus.workspace = true
gloo-timers = { version = "0.3.0", features = ["futures"] }
tracing = "0.1.41"
