[package]
name = "by-axum"
version = "0.2.10"
edition = "2021"
description = "Library satisfying Biyard API convention"
license = "Apache-2.0"
keywords = ["axum", "lambda", "api", "serverless"]
repository = "https://github.com/biyard/rust-sdk/tree/main/packages/by-axum"

[dependencies]
dioxus-aws = { version = "0.6.4", optional = true }
http = { version = "1.1.0", optional = true }
lambda_http = { version = "0.13.0", optional = true }
lambda_runtime = { version = "0.13.0", optional = true }
serde = "1.0.217"
slog = "2.7.0"
slog-term = "2.9.1"
slog-async = "2.8.0"
static_str_ops = "0.1.2"
tower = { version = "0.5.1" }
tokio = { version = "1.41.1", features = ["net"] }
tower-http = { version = "0.6.2", features = [
    "cors",
    "compression-gzip",
    "compression-deflate",
    "trace",
] }
tower-service = "0.3.3"
aide.workspace = true
axum.workspace = true
schemars.workspace = true
by-types = { workspace = true, features = [ "server" ] }
serde_json = "1.0.135"
tracing-subscriber = "0.3.19"
tracing = "0.1.41"
rest-api.workspace = true
jsonwebtoken = "9.3.0"

[features]
lambda = ["dioxus-aws", "lambda_runtime", "lambda_http", "http"]
