[package]
name = "dioxus-translate-types"
version = "0.1.2"
authors.workspace = true
edition.workspace = true
description = "Libraries for internalization on Dioxus"
license = "MIT"
keywords = ["dioxus", "web", "i18n", "translate"]
repository = "https://github.com/biyard/rust-sdk/tree/main/packages/dioxus-translate-types"

[dependencies]

[features]
ko = []
