[package]
name = "google-wallet"
version = "0.1.2"
authors.workspace = true
description = "Blockchain wallet management library with Google account"
edition.workspace = true
repository = "https://github.com/biyard/rust-sdk/tree/main/packages/google-wallet"
license.workspace = true

[dependencies]
base64 = "0.22.1"
candid = "0.10.11"
dioxus = { workspace = true, features = ["web"] }
dioxus-oauth = { path = "../dioxus-oauth", version = "0.6.*" }
gloo-storage = "0.3.0"
reqwest = { workspace = true, features = ["blocking", "json"] }
ring = { version = "0.17.8", features = ["wasm32_unknown_unknown_js"] }
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10.8"
simple_asn1 = "0.6.2"
tracing = "0.1.41"

[features]
default = []
