[package]
name = "by-components"
version = "0.1.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Biyard components"
repository = "https://github.com/biyard/rust-sdk/tree/main/packages/by-components"

[dependencies]
dioxus.workspace = true
wasm-bindgen = { version = "0.2.*", features = ["serde-serialize"] }
wasm-bindgen-futures = { version = "0.4.*" }
web-sys = { version = "0.3.*", features=["Navigator", "HtmlCollection","EventTarget"] }
tracing = { version = "0.1.40" }
serde_json.workspace = true
serde.workspace = true
js-sys = "0.3.77"
serde-wasm-bindgen = "0.6.5"
num-format = "0.4.4"
dioxus-translate.workspace = true