[package]
name = "dioxus-aws"
version = "0.6.17"
edition = "2021"
description = "Library for deploying Dioxus apps to AWS Serverless (AWS Lambda, S3, CloudFront, Route53)."
license = "MIT"
keywords = ["dioxus", "fullstack", "aws", "serverless"]
repository = "https://github.com/biyard/rust-sdk/tree/main/packages/dioxus-aws.git"

[dependencies]
dioxus = { workspace = true,  features = ["router"] }
dioxus-fullstack = { workspace = true }
dioxus-cli-config = { workspace = true, optional = true }

tracing = "0.1.40"

tokio = { version = "1.39.1", features = ["full"], optional = true }
axum = { version = "0.7.5", optional = true }

lambda_http = { version = "0.12.0", optional = true }
lambda_runtime = { version = "0.12.0", optional = true }
tower = { version = "0.4.13", features = ["util"], optional = true }
http = { version = "1.1.0", optional = true }
tower-layer = { version = "0.3.3", optional = true }
tower-service = { version = "0.3.3", optional = true }
axum-core = { version = "0.4.5", optional = true }

[features]
default = []
web = ["dioxus/web", "dioxus-fullstack/web", "dioxus/fullstack"]
server = ["dioxus/fullstack", "dioxus-fullstack/axum", "dioxus-fullstack/server", "axum", "tokio/full", "dioxus-cli-config", "axum-core", "tower-layer", "tower-service", "tokio"]
web-only = ["web"]
lambda = ["server", "tower", "lambda_http", "lambda_runtime", "http"]
tokio = ["dep:tokio"]
