[package]
name = "dioxus-oauth"
version = "0.6.5"
edition = "2021"
description = "Library for using OAuth in dioxus"
license = "MIT"
keywords = ["dioxus", "web", "oauth", "popup"]
repository = "https://github.com/biyard/rust-sdk/tree/main/packages/dioxus-oauth"

[dependencies]
dioxus = { workspace = true }
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
url = { version = "2.5.2" }
tracing = "0.1.40"
serde = "1.0.204"

web-sys = { version = "0.3.72" }
wasm-bindgen = { version = "0.2.100" }
wasm-bindgen-futures = { version = "0.4.50" }
serde_json = "1.0.133"
serde-wasm-bindgen = "0.6.5"

[features]
web = []
